directories:
  - code: raw
    parts: ['data', 'hydrometry']
  - code: storage
    parts: ['warehouse', 'hydrometry']
nodes:
  - code: stations
    url: 'https://environment.data.gov.uk/hydrology/id/stations.json?_limit=10000'
    basename: "stations.json"